### ISSUE TITLE
`transition: var(--something)` gets converted to `false(--something)`

### ISSUE THREAD

**Issue by brianmhunt** [cssinjs/css-vendor#112]
In JSS, which uses this plugin:

```css
cls: {
  transition: 'var(--something)'
}
```

gets converted (via [`supportedValue`](https://github.com/cssinjs/css-vendor/blob/master/src/supported-value.js#L41)) to

```css
.cls-0-1-7 {
  transition: false(--something);
}
```

Namely, the `var` is being converted to `false`.

If I've tracked the stack appropriately, the issue appears to [occur here](https://github.com/cssinjs/css-vendor/blob/master/src/supported-value.js#L73):

>   prefixedValue = prefixedValue.replace(transPropsRegExp, prefixTransitionCallback)

See downstream issue in the JSS library https://github.com/cssinjs/jss/issues/1099
