### ISSUE TITLE
`transition: var(--something, var(--fallback))` gets converted to `var(--something, false(--fallback))`

### ISSUE THREAD

**Issue by DioEraclea** [cssinjs/css-vendor#244]
In JSS, which uses this plugin:

```javascript
example: {
  transition: 'var(--something, var(--fallback))'
}
```

gets converted to

```css
.example-1-2-3 {
  transition: var(--something, false(--fallback))
}
```

Namely, the fallback var is being converted to `false`.

This issue is similar to #112
